In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import Point
import geopandas as gpd
import geoplot as gplt
import datetime
import pyproj
from shapely.geometry import Polygon, MultiPolygon,Point, MultiPoint
from shapely.ops import nearest_points
import fiona; fiona.supported_drivers

{'ARCGEN': 'r',
 'AeronavFAA': 'r',
 'BNA': 'raw',
 'DGN': 'raw',
 'DXF': 'raw',
 'ESRI Shapefile': 'raw',
 'GPKG': 'rw',
 'GPSTrackMaker': 'raw',
 'GPX': 'raw',
 'GeoJSON': 'rw',
 'Idrisi': 'r',
 'MapInfo File': 'raw',
 'OpenFileGDB': 'r',
 'PCIDSK': 'r',
 'SEGY': 'r',
 'SUA': 'r'}

In [2]:
def convert_poly(polygon):
    NYSP1983 = pyproj.Proj(init="ESRI:102718", preserve_units=True)
    gis = []
    for coo in list(polygon.exterior.coords):
        x,y = coo
        gis.append(NYSP1983(x, y, inverse=True))
    return Polygon(gis)

def convert_multi(multi):
    if isinstance(multi, MultiPolygon):
        out = []
        for poly in multi.geoms:
            out.append(convert_poly(poly))
        return MultiPolygon(out)
    else:
        return convert_poly(multi)

In [3]:
def nearest(row, geom_union, df1, df2, geom1_col='geometry', geom2_col='geometry', src_column=None):
    """Find the nearest point and return the corresponding value from specified column."""
    # Find the geometry that is closest
    nearest = df2[geom2_col] == nearest_points(row[geom1_col], geom_union)[1]
    # Get the corresponding value from df2 (matching is based on the geometry)
    value = df2[nearest][src_column].get_values()[0]
    return value

In [5]:
firebox_all = gpd.read_file('data/firebox_all.geojson')

In [6]:
firebox_all.head()

,ALARM_BOX_BOROUGH,ALARM_BOX_NUMBER,address,count2_2013,count2_2014,count2_2015,count_2013,count_2014,count_2015,number,geometry
0,BROOKLYN,14,Gardner Ave & Meeker Ave,0.0,0.0,0.0,0.0,0.0,0.0,B0014,POINT (-73.93253 40.72795)
1,BROOKLYN,15,Gardner Ave & Cherry St,0.0,0.0,0.0,0.0,0.0,0.0,B0015,POINT (-73.93146 40.72563)
2,BROOKLYN,18,Bridgewater St & Varick St,0.0,0.0,0.0,0.0,0.0,0.0,B0018,POINT (-73.93622000000001 40.72748)
3,BROOKLYN,20,Meserole Ave & Banker St,0.0,0.0,0.0,0.0,0.0,0.0,B0020,POINT (-73.95612 40.72601)
4,BROOKLYN,23,Commercial St & Clay St,0.0,0.0,0.0,0.0,0.0,0.0,B0023,POINT (-73.95865000000001 40.73626)

In [17]:
pluto14_b = gpd.read_file('data/mappluto_14v2/Brooklyn/BKMapPLUTO.shp')
pluto14_q = gpd.read_file('data/mappluto_14v2/Queens/QNMapPLUTO.shp')
pluto14_x = gpd.read_file('data/mappluto_14v2/Bronx/BXMapPLUTO.shp')
pluto14_r = gpd.read_file('data/mappluto_14v2/Staten_Island/SIMapPLUTO.shp')

In [18]:
print(pluto14_r.shape)

(123538, 87)

In [28]:
def convert_coo(data):
    geometry = data.apply(
        lambda location: convert_multi(location.geometry), 
        axis='columns'
    )
    data.geometry = geometry
    data['centroid'] = data.centroid
    #data.drop(columns=['centroid'], inplace=True)
    return data

In [29]:
pluto14_b = convert_coo(pluto14_b)
pluto14_q = convert_coo(pluto14_q)
pluto14_x = convert_coo(pluto14_x)
pluto14_r = convert_coo(pluto14_r)

In [30]:
pluto14_b.head()

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,EDesigNum,APPBBL,APPDate,PLUTOMapID,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area,geometry,centroid
0,BK,3,1,302,21,3002,13,33,11201,L118,...,None,0.0,None,1,14v2,0,3006.050658,431742.539527,POLYGON ((-77.51985448725486 40.11248877973426...,POINT (-77.51985449398377 40.11248877801885)
1,BK,6,100,302,21,None,13,33,11201,E207,...,None,0.0,None,1,14v2,0,313.396765,2364.799200,POLYGON ((-77.51985448094894 40.11248878069821...,POINT (-77.51985448110331 40.11248878023658)
2,BK,20,21,302,21,3008,13,33,11201,L118,...,E-231,0.0,None,1,14v2,0,465.899606,12928.661246,POLYGON ((-77.51985449479864 40.11248877539929...,POINT (-77.51985449570145 40.11248877573914)
3,BK,32,140,302,21,3010,13,33,11201,L118,...,None,0.0,None,1,14v2,0,267.251602,3343.628520,POLYGON ((-77.51985448977861 40.11248877360515...,POINT (-77.51985449000618 40.11248877323641)
4,BK,35,11,302,21,1005,13,33,11201,E205,...,None,0.0,None,1,14v2,0,184.063087,1636.684931,"POLYGON ((-77.51985452687724 40.1124887716994,...",POINT (-77.51985452725793 40.11248877154252)

In [29]:
pluto14_b.to_file('pluto14.geojson', driver="GeoJSON")

In [31]:
def find_alarm(boro, data):
    firebox_tmp = firebox_all[firebox_all.ALARM_BOX_BOROUGH==boro]
    unary_union = firebox_tmp.unary_union
    #len(unary_union)
    id_list = []
    for i in range(data.shape[0]):
        x = data.iloc[i]
        id_list.append(nearest(x,geom_union=unary_union, df1=data, df2=firebox_tmp, 
                               geom1_col='centroid', src_column='number'))
        if i%1000==0:
            print(i)
    return id_list

In [ ]:
pluto14_b['nearest_id'] = find_alarm('BROOKLYN', pluto14_b)

0
1000
2000

In [54]:
pluto14_b.drop(columns=['centroid'], inplace=True)
pluto14_b.to_file('data/pluto14_b.geojson', driver="GeoJSON")